# Generated by Django 6.0 on 2025-12-14 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('access_level', models.CharField(choices=[('WR', 'Worker'), ('OP', 'Operator'), ('AD', 'Admin')], default='WR', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='sign',
            field=models.CharField(default=None, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.car'),
        ),
        migrations.AddField(
            model_name='report',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='main.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.employeeposition'),
        ),
    ]
