# Generated by Django 6.0 on 2025-12-14 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee_employeeposition_car_sign_alter_car_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Транспортное средство', 'verbose_name_plural': 'Транспотные средсва'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='employeeposition',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
        migrations.RemoveField(
            model_name='employeeposition',
            name='title',
        ),
        migrations.AddField(
            model_name='employeeposition',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='Наименование'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='car',
            name='sign',
            field=models.CharField(max_length=6, verbose_name='Регистрационный знак'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='patronymic',
            field=models.CharField(max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.employeeposition', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='access_level',
            field=models.CharField(choices=[('WR', 'Worker'), ('OP', 'Operator'), ('AD', 'Admin')], default='WR', max_length=2, verbose_name='Уровень доступа'),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='description',
            field=models.TextField(max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='report',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.car', verbose_name='Т/С'),
        ),
        migrations.AlterField(
            model_name='report',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Одобрен'),
        ),
    ]
