# Generated by Django 6.0 on 2025-12-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_car_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeposition',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
    ]
