# Generated by Django 6.0 on 2025-12-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_employeeposition_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='login',
            field=models.CharField(default='Default', max_length=255, verbose_name='Логин'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='Default', max_length=1000, verbose_name='Пароль'),
            preserve_default=False,
        ),
    ]
